yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Модель для групп постов"""
    title = models.CharField('title для страницы группы', max_length=200)
    slug = models.SlugField('url-адрес для страницы группы', unique=True)
    description = models.TextField('Описание для страницы группы')

    class Meta:
        verbose_name = 'Группа постов'
        verbose_name_plural = 'Группы постов'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    """Модель для постов"""
    text = models.TextField(
        verbose_name = 'Текст поста',
        help_text='Введите текст для поста',
    )
    #pub_date = models.DateTimeField(
    #    verbose_name = 'Дата публикации',
    #    auto_now_add=True,
    #)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа поста',
        related_name='posts',
        help_text='Выберите группу из списка',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор поста',
        related_name='posts',
    )
    image = models.ImageField(
        verbose_name = 'Картинка',
        upload_to='posts/image/',
        blank=True
    )  

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        # ordering = ('-pub_date',)
        # ordering = ('-created',)

    def __str__(self):
        return self.text[:15]

class Comment(CreatedModel):
    """Модель комментариев"""
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Комментарий',
        related_name='comments',
        help_text='Опишите комментарий',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария',
        related_name='comments',
    )
    text = models.TextField(
        verbose_name = 'Текст комментария',
        help_text='Введите текст для комментария',
    )
    #created = models.DateTimeField(
    #    verbose_name = 'Дата создания комментария',
    #    auto_now_add=True,
    #)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Введите какой нибудь текст... 😥'
        )
        self.fields['group'].empty_label = (
            'Выберите группу, если желаете 🙂'
        )

    class Meta:
        # лейблы как я понял в модели прописаны
        model = Post
        fields = ('text', 'group', 'image')
        '''
        help_texts = {
            'text': 'Введите текст для поста',
            'group': 'Выберите группу из списка'
        }'''

class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Введите комментарий... 😥'
        )

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Group, Post, User
from .utils import page


def index(request):
    """Функция главной страницы"""
    post_list = Post.objects.all()
    page_obj = page(request, post_list, settings.LIMIT)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """функция группы постов"""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = page(request, post_list, settings.LIMIT)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """функция страницы порфиля автора"""
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author)
    page_obj = page(request, post_list, settings.LIMIT)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)
'''
def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related('author', 'group'),
        pk=post_id
    )
    count = post.author.posts.count()
    comments = post.comments.select_related('author')
    context = {
        'post': post,
        'comments': comments,
        'count': count,
        'form': CommentForm(),
    }
    return render(request, 'posts/post_detail.html', context)'''

def post_detail(request, post_id):
    """функция подробной информации о посте"""
    post = get_object_or_404(Post, id=post_id)
    comments = Comment.objects.filter(post=post)
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """функция создания нового поста"""
    # if request.method == 'POST':
    form = PostForm(request.POST or None,
                    files=request.FILES or None,)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/create.html', {'form': form})
    # form = PostForm()
    # return render(request, 'posts/create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """функция редактирования поста"""
    post = get_object_or_404(Post, id=post_id)
    if request.user.id != post.author.id:
        return redirect('posts:post_detail', post_id=post.id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    context = {
        'form': form,
        'is_edit': True,
        'post_id': post_id,
    }
    return render(request, 'posts/create.html', context)

@login_required
def add_comment(request, post_id):
    # Получите пост и сохраните его в переменную post.
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post 
        comment.save()
    return redirect('posts:post_detail', post_id=post_id) 

yatube/templates/posts/create.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактор поста
  {% else %}
    Новый пост
  {% endif %}  
{% endblock %}

{% block content %}
{% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Добавить пост
            {% endif %}                  
          </div>
          <div class="card-body">
            {% include 'includes/err.html' %}
            <form method="post"
              enctype="multipart/form-data"
              {% if is_edit %}
                action="{% url 'posts:post_edit' post_id %}"
              {% else %}  
                action="{% url 'posts:post_create' %}"
              {% endif %}
            > 
              {% csrf_token %}
              

              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ fielad.label }}
                    {% if field.field.reqired %}
                      <span class="required text-danger" >*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                  {%if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted"
                    >
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить пост
                  {% else %}
                    Добавить пост
                  {% endif %}  
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}


{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}


{% block content %}
  <div class="container py-5"> 
    <h1>{{ group.title }}</h1>
    {{ group.description|linebreaks  }}
    <hr>
    {% for post in page_obj %}
      {% include 'includes/post.html' %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  
    {% include 'includes/paginator.html' %}
  
    <br>
    <a href="{% url 'posts:index' %}">Последние обновления</a>
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %} 


{% block title %}
  Последние обновления на сайте
{% endblock %} 


{% block content %}
  <div class="container py-5"> 
    <h1>Последние обновления на сайте</h1>
    <hr>
    {% for post in page_obj %}
      {% include 'includes/post.html' with show_group_link=True %}
      {% if not forloop.last %}
        <hr>
      {% endif %}
    {% endfor %}
  
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 

{% block title %}
  Пост  {{ post.text|truncatechars:30 }}
{% endblock %}
{% load thumbnail %}
{% load user_filters %}

{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <!--Дата публикации:  {{ post.pub_date|date:'d E Y' }}-->
          Дата публикации:  {{ post.created|date:'d E Y' }}
        </li>
        {%if post.group %}   
          <li class="list-group-item">
            Группа: {{ post.group.title }} <br><!-- Название группы -->
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }} <!--Лев Толстой-->
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{ post.author.posts.count }} </span>
          {% comment "" %}Всего постов автора:  <span > {{ posts_count }}  </span>  {% endcomment %} 
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}"> <!--max-width in class base-->
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaks }} 
      </p>
      {% if user == post.author %}
      <!--по-моему в меню кнопка красивее смотрелась-->
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
            Редактировать пост
          </a>
      {% endif %}
    </article>
    <!--Форма добавления комментария-->
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}      
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}

    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %} 

  </div> 
</div>
{% endblock %} 
   

yatube/templates/posts/profile.html
{% extends 'base.html' %} 

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %} 

{% block content %} 
  <div class="container py-5"> 
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>  
    {% for post in page_obj %}
      {% if author %}
        {% include 'includes/post.html' with not_author_page=True %}
      {% endif %}
      {%if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}